version: '3.8'

services:
  backend:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: eth-backend
    working_dir: /app
    volumes:
      - ./:/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
